### ISSUE TITLE
Support for Netgear AC1200

### ISSUE THREAD

**Issue by femidof** [morrownr/7612u#15]
I have a problem getting my wifi usb adapter working with my Kali Linux and Ubuntu, I’m a noob to this, please pardon me. 

The adapter is a: 
Netgear AC1200, 
model A6210,
With a Mediatek chipset MT7612U I believe 
My Kali is currently running on the 6.0amd64 kernel 

All possible fixes I tried were either deprecated, not working or breaking.

Anyone knows a way around this? 

Tnx

**Comment by morrownr** [comment]
@femidof 

Be careful trying things because a lot of info on the net is not good these days. Recommend you restrict internet searches to one year or less generally speaking.

Post the results of the following commands with the adapter in a USB3 port:

uname -r
lsusb
lsusb -t
iw dev

**Comment by morrownr** [comment]
@femidof 

It sounds like something is wrong with Kali. We can either try to figure it out or you can reinstall Kali into a formatted partition. This is what I would recommend.

**Comment by femidof** [comment]
So I setup a new environment because I believed I have made so many obsolete installation steps for the driver,

**Comment by morrownr** [comment]
@femidof 

> VMware, Inc.

The lightbulb comes on. You are running in a VM. That is the cause of the usb wifi adapter not working. This can be corrected but I am not the one to help as I run 100% bare metal. Recommend you check in on the VMWare support forums.

FYI: You Netgear A6210 adapter does not require a driver in any modern, supported Linux unless it is a distro that does not automatically install the firmware... then you would have to install the firmware. It is highly likely that Kali installs the firmware so you should be good to go.

Words of advice: When looking for guidance on how to do something in Linux, set your search engine to only show links that are one year old or less. Things evolve. Eight years ago you would have needed to install a driver for your adapter, today you need to do nothing but plug it in. In fact, if you install that eight year old driver, it may cause problems. Remember that `sudo` is a weapon of mass destruction on a Linux system. Do not use it until you double check that you are doing the right thing.

Nick

**Comment by femidof** [comment]
oops thank you, i forgot to mention i was running this on a Virtual Machine. I was able to make it run on a windows server after so many hacks. But for linux, for unknown reasons the terminal freezes and until I disconnect the usb, i get no return. When I get a response after unmounting, I see the Netgear Inc adapter. And I have tested this on different distro, Ubuntu, Kali and Nobara

**Comment by femidof** [comment]
How do you suggest I debug when the terminal hangs... when i run lsusb...
definitely theres an error somewhere thats causing it.

**Comment by morrownr** [comment]
> How do you suggest I debug when the terminal hangs... when i run lsusb...
definitely theres an error somewhere thats causing it.

This is just me but if it were me working this issue, I would remove VMWare and install Virtualbox. I rarely use VM's but I usually keep an installation of Virtualbox around. In my driver repos, in the FAQ, I post the following url for folks trying to set up a usb wifi adapter:

https://null-byte.wonderhowto.com/forum/wifi-hacking-attach-usb-wireless-adapter-with-virtual-box-0324433/

If you read the article, that should give you an idea of what needs to be done. The issue with VM's is one of what operating system owns what hardware and you have to set that up. The VM has to own the adapter for this to be successful.

Let me know.

**Comment by femidof** [comment]
Thank you so much, I appreciate
