### ISSUE TITLE
hiveos error

### ISSUE THREAD

**Issue by taigoil** [morrownr/7612u#4]
After installing the driver, it shows that 

[12.760617][ T391]mt76x2u 2-1:1.0: vendor request req:07 off:09a8 failed:-110
[15.960510][ T391]mt76x2u 2-1:1.0: vendor request req:06 off:09a8 failed:-110

and no wireless card found. 

usb link seems no problem using lsusb, there shows the usb wireless device linked.

**Comment by taigoil** [comment]
I have another device 8814au, it is normal after installing your drivers. - the same computer.

**Comment by morrownr** [comment]
Hi @taigoil 

I am a little confused. Can you paste the output of:

$ sudo uname -a && mokutil --sb-state && lsusb && rfkill list all && dkms status && iw dev

When you say "After I installed the driver..."

What driver did you install?

**Comment by taigoil** [comment]
Sorry late reply, I check all the steps by following your instructions and finally I found the issue perhaps that it is a 7612un not 7612u chipset, any suggest? Thx.

**Comment by morrownr** [comment]
You are asking questions but not giving me anything to work with. Please tell me what 7612un based usb wifi adapter that you have and what problem you were seeing?
